### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by matthewmueller** [kewde/electron-sandbox#4]
just wanted to say thanks for putting this together. it's very useful information and immediately actionable :-)

**Comment by kewde** [comment]
@matthewmueller 

Thank you for your kind words, I greatly appreciate it.
Please note that this repository is still a work in progress, it hasn't had much review yet and I'm still actively reaching out (or should I rather say, harassing hehe) to people who have the knowledge and want to help. I still believe that in its current state, it's an improvement on the status quo.

**Comment by kewde** [comment]
@matthewmueller if you plan on packaging your applications and distributing it on other platforms (windows, linux etc) then keep an eye on #7
